// Get the incoming question from the chat trigger
const incomingQuestion = $input.first().json.query.chatInput;

// Define your predefined questions
const predefinedQuestions = [
  "youtube",
"What is NerveSpa?",
 "What conditions and symptoms can NerveSpa support?",
      "How can my clinic order NerveSpa or get a demo?",
      "What are NerveSpa’s pricing options?",
      "what is the difference between biphasic and monophasic waveforms",
      "What makes NerveSpa unique?",
      "Is NerveSpa FDA-registered?",
      "Is NerveSpa covered by insurance?",
      "Does NerveSpa replace medical care?",
      "How should the battery be maintained?",
      "What modes does the system use?",
      "Why water-based therapy?",
      "What improvements do patients report?",
      "What consumables are used with the system?",
      "What are NerveSpa Condtive Foot pads, socks and Gloves?",
      "How are the foot pad and gloves used in therapy?",
      "What is the NerveSpa QuakePlate?",
      "How is the QuakePlate used?",
      "Who should not use the QuakePlate?",
      "What outcomes are expected with the QuakePlate?",
      "What is the NerveSpa KneePro?",
      "How is the KneePro used?",
      "Who should not use the KneePro?",
      "What outcomes are expected with the KneePro?",
      "What is the NerveSpa ShoulderPro?",
      "How is the ShoulderPro used?",
      "Who should not use the ShoulderPro?",
      "What outcomes are expected with the ShoulderPro?",
      "What is the NerveSpa Vibe?",
      "How is the Vibe used?",
      "Who should not use the Vibe?",
      "What outcomes are expected with the Vibe?",
      "What topical products are part of NerveSpa?",
      "What is the Plantar Fasciitis & Heel Spur Cream?",
      "How should Plantar Fasciitis Cream be applied?",
      "What outcomes are expected from NerveSpa topicals?",
      "Are NerveSpa creams and roll-ons safe for everyone?",
      "How should NerveSpa creams and roll-ons be applied?",
      "Do topicals replace medical care?",
      "How do topicals integrate with the full NerveSpa system?",
      "Are demo resources available for creams and roll-ons?",
      "What support resources are available for providers?",
      "What resources are available for patients?",
      "How do clinics contact NerveSpa support?",
      "How do patients contact NerveSpa?",
      "How do clinics order or reorder supplies?",
      "How do patients receive consumables or supplements?",
      "What outcomes are expected from the QuakePlate?",
      "What outcomes are expected from the KneePro?",
      "What outcomes are expected from the ShoulderPro?",
      "What outcomes are expected from the Vibe?",
      "What outcomes are expected from supplements?",
      "Can supplements be combined with NerveSpa devices?",
      "Are supplements safe for everyone?",
      "what are ODF's and why are they effective",
      "What ingredients are in N1 Nerve+?",
      "How does N1 Nerve+ support improve nerve health?",
      "What makes the N1 Nerve+ oral dissolvable film unique?",
      "What ingredients are in N1 Skinny Blend?",
      "How does N1 Skinny Blend support weight management and metabolism?",
      "What ingredients are in N1 Gut Support?",
      "How does N1 Gut Support improve digestion and nutrient absorption?",
      "What makes N1 Gut Support unique?",
      "What ingredients are in the Super Flex Joint Formula?",
      "How does the Super Flex Joint Formula support joint health?",
      "What makes the Super Flex Joint Formula unique?",
      "What ingredients are in the Blood Flow Super Formula?",
      "How does the Blood Flow Super Formula support neuropathy and circulation?",
      "What makes the Blood Flow Super Formula unique?",
      "What ingredients are in the Nerve Rebuilder supplement?",
      "How does the Nerve Rebuilder support nerve health and regeneration?",
      "What makes the Nerve Rebuilder unique?",
      "What ingredients are in the ImmunityGut Super Formula?",
      "How does the ImmunityGut Super Formula support gut and immune health?",
      "What makes the ImmunityGut Super Formula unique?",
      "Why is compliance important for supplement outcomes?",
      "What is the Nerve Target Roll-On?",
      "How should the Nerve Target Roll-On be applied?",
      "What outcomes are expected from creams and roll-ons?",
      "Are topicals safe for everyone?",
      "Can topicals be used with other NerveSpa therapies?",
      "Do topicals replace oral supplements or devices?",
      "Why is compliance important for topical outcomes?",
      "What support resources exist for topical use?",
      "How do patients reorder creams and roll-ons?",
      "Do topicals require FDA clearance?",
      "Who is PMT in relation to NerveSpa?",
      "What certifications does PMT hold?",
      "Where are NerveSpa products manufactured?",
      "Where can FDA listings be verified?",
      "What is the NerveSpa return policy?",
      "Does NerveSpa replace medical treatment?",
      "Who determines how NerveSpa should be used?",
      "Do NerveSpa products require direct provider supervision?",
      "What should patients do if discomfort or side effects occur?",
      "What if stimulation feels weak?",
      "How quickly are products shipped?",
      "How are returns processed?",
      "How do clinics contact NerveSpa for support?",
      "What role do patients play in outcomes?",
      "Where can patients get NerveSpa creams and roll-ons?",
      "What support resources are available for topicals?",
      "What do patients say about creams and roll-ons?",
      "How do patients or clinics order topicals?",
      "Do providers or clinics receive training for topical use?",
      "Can topicals be used long-term?",
      "Does insurance cover consumables like salts or garments?",
      "What is HCPCS code E0720?",
      "How do clinics order NerveSpa?",
      "How do clinics bill insurance for NerveSpa?",
      "How do I set up a provider account?",
      "How much does NerveSpa cost for patients?",
      "Are there minimum order requirements?",
      "What products are included in a starter kit?",
      "Are bundles available for patients?",
      "Who should patients contact for technical issues?",
      "Are starter kits or bundles for clinics available?",
      "What outcomes are expected from bundles?",
      "What training do providers receive?",
      "How can patients learn proper use?",
      "What outcomes are expected from conductive garments?",
      "Is NerveSpa safe for everyone?",
      "What support resources are available?",
      "Can NerveSpa be used with other treatments?",
      "Can NerveSpa be used long-term?",
      "Can multiple NerveSpa modalities be used in the same day?",
      "What happens after the initial 60–90 day program?",
      "What lifestyle changes support NerveSpa therapy?",
      "What research supports NerveSpa therapies?",
      "Who decides if NerveSpa is appropriate?",
      "What should patients do if discomfort or side effects occur?",
      "What support resources are available for patients?",
      "Who should not use NerveSpa Creams and Roll-Ons?",
      "Can NerveSpa topicals be combined with device therapies?",
      "How do patients reorder NerveSpa supplements?",
      "How do patients reorder consumables like salts, electrodes, or lead wires?",
      "Can NerveSpa supplements be combined with device therapies?",
      "What lifestyle changes can support NerveSpa therapy?",
      "Contact",
      "phone number",
      "email",
      "Who should NOT use NerveSpa Hand & Footbath?",
      "What are NerveSpa Conductive Garments (gloves/socks)?",
      "How do I use the conductive gloves or socks?",
      "Who should NOT use the conductive garments?",
      "Who should NOT use NerveBeam?",
      "What is QuakePlate and what does it do?",
      "How do I use QuakePlate safely?",
      "Who should NOT use QuakePlate?",
      "What is NerveSpa Knee Pro?",
      "How do I set up Knee Pro?",
      "How do I care for Knee Pro electrodes and when to replace?",
      "What does Knee Pro therapy feel like?",
      "Who should NOT use Knee Pro?",
      "What is NerveSpa Shoulder Pro?",
      "How do I set up Shoulder Pro?",
      "How do I care for Shoulder Pro electrodes and when to replace?",
      "What does Shoulder Pro therapy feel like?",
      "Who should NOT use Shoulder Pro?",
      "Can children use NerveSpa products?",
      "Who do I contact for technical support?",
      "What is the turnaround time for repairs or replacements?",
      "What consumables come with NerveSpa systems?",
      "How do I reorder consumables and accessories?",
      "What results can I expect from using NerveSpa Footbath?",
      "What results can I expect from using Conductive Garments?",
      "What results can I expect from using QuakePlate?",
      "What results can I expect from using Knee Pro?",
      "What results can I expect from using Shoulder Pro?",
      "What does treatment feel like?",
      "How quickly will I notice improvements?",
      "Are results permanent?",
      "Can NerveSpa be combined with other therapies?",
      "Can I use NerveSpa if I have a pacemaker?",
      "Can I use NerveSpa during pregnancy?",
      "Can I sleep with a NerveSpa device running?",
      "Can NerveSpa products be used daily?",
      "Can NerveSpa help with arthritis?",
      "Is NerveSpa HSA/FSA eligible?",
      "Do I need a prescription for NerveSpa?",
      "Can NerveSpa replace my medications?",
      "How do I replace gel electrodes?",
      "How do I charge my NerveSpa device?",
      "How do I troubleshoot if my device will not power on?",
      "Can I travel with my NerveSpa device?",
      "Are NerveSpa products FDA cleared?",
      "Do NerveSpa products come with instructions?",
      "How do I access NerveSpa demo videos?",
      "Can I share my NerveSpa device with others?",
      "Are there clinical studies on NerveSpa?",
      "What is included in the starter kit for each product?",
      "How do I know which NerveSpa product is right for me?",
      "Can I combine multiple NerveSpa therapies?",
      "What are the benefits of red vs infrared light?",
      "What is the difference between NerveSpa Footbath and Conductive Garments?",
      "Can I use QuakePlate together with Footbath?",
      "How do I know if my electrodes are still effective?",
      "Can I use NerveSpa with compression socks or braces?",
      "Are there side effects from NerveSpa?",
      "What precautions should I take before starting therapy?",
      "Can I return a NerveSpa product if it doesn’t work for me?",
      "What conditions does NerveSpa support?",
      "Are NerveSpa products safe to use with medications?",
      "Do NerveSpa devices need calibration?",
      "Where can I find NerveSpa product manuals?",
      "Where can I watch NerveSpa YouTube videos?",
      "Can I get medical advice from NerveSpa?",
      "Show me a demo",
      "Show me demos for all devices",
      "Show me a demo for Footbath",
      "Show me a demo for Conductive Garments",
      "Show me a demo for LED Wrap",
      "Show me a demo for Power Wrap",
      "Show me a demo for QuakePlate",
      "Show me a demo for Knee Pro",
      "Show me a demo for Shoulder Pro",
      "Troubleshoot Knee Pro",
      "Troubleshoot Shoulder Pro",
      "Welcome (Clinic)",
      "Main Menu (Clinic)",
      "Choose a device",
      "Troubleshoot QuakePlate",
      "Show videos",
      "Product video",
      "How do providers prescribe or implement NerveSpa?",
      "How long is a typical session?",
      "How often should the system be used?",
      "How do providers determine which topical to recommend?",
      "Can topicals be used in clinics during therapy sessions?",
      "How are supplements usually prescribed?",
      "Do providers need to prescribe topicals?",
      "How do providers bill insurance for NerveSpa?",
      "Do providers prescribe supplements or can patients self-select?",
      "How often should conductive garments be used?",
      "How long is a NerveBeam session?",
      "How long is a Knee Pro session and what are the modes?",
      "How often should Knee Pro be used?",
      "How long is a Shoulder Pro session and what are the modes?",
      "How often should Shoulder Pro be used?",
      "Is NerveSpa safe for seniors to use at home?",
      "How do I store NerveSpa products between sessions?",
      "How often should consumables be replaced?",
      "How long is the warranty period?",
      "Can I use QuakePlate before or after Knee/Shoulder Pro sessions?",
      "Can NerveSpa devices be used in clinics or only at home?",
      "What should I do if I feel discomfort during a session?",
      "How long do NerveSpa devices typically last?",
      "How long is a QuakePlate session?",
      "How often should QuakePlate be used?",
      "How often should the LED Wrap be used?",
      "How often should the Power Wrap be used?",
      "is 22,000 mW power coming out of LED's more effective therapeuticaly than 12000mW power coming out of lasers?",
      "What are the pros and cons of a Wrappable LED device vs. a physical hard device",
      "Does the LED wrap Produce a lot of heat",
      "Why doesnt the LED wrap have higher Joules",
      "The Health Light LED device markets a high amount of joules, why doesnt the nerve beam have as high joules?",
      "What are NerveSpa LED Wraps?",
      "Who should not use  Wraps?",
      "What is the NerveBeam LED Light Therapy Wrap?",
      "How is the NerveBeam LED Wrap used?",
      "Who should not use the NerveBeam LED Wrap?",
      "What is the NerveBeam Cold Laser?",
      "How is the Cold Laser used?",
      "Who should not use the Cold Laser?",
      "What is the PowerWrap?",
      "How is the PowerWrap used?",
      "Who should not use the PowerWrap?",
      "What outcomes are expected with Cold Laser or PowerWrap therapy?",
      "What outcomes are expected with Wrap therapy?",
      "What outcomes are expected from the LED Wrap?",
      "What outcomes are expected from the Cold Laser?",
      "What outcomes are expected from the PowerWrap?",
      "What if the LED Wrap does not light?",
      "What if Wraps feel uncomfortable?",
      "What outcomes are expected from Wraps?",
      "Who should not use NerveSpa Wraps?",
      "What is NerveBeam (LED/Power Wrap)?",
      "How do I use the NerveBeam LED/Power Wrap?",
      "How do I clean and store the NerveBeam wrap?",
      "What accessories are included with each system?",
      "What results can I expect from using NerveBeam LED/Power Wraps?",
      "How do I clean and maintain NerveBeam wraps?",
      "What is the difference between LED Wrap and Power Wrap?",
      "What accessories require replacement most often?",
      "What is the NerveSpa Hand & Foot Neuropathy System?",
      "How does the Hand & Foot Neuropathy System work?",
      "How should the Hand & Foot Neuropathy System be set up?",
      "What is the Nerve & Neuropathy Cream?",
      "How should the Nerve & Neuropathy Cream be applied?",
      "Who should not use the Nerve & Neuropathy Cream?",
      "What outcomes are expected with the Nerve & Neuropathy Cream?",
      "What is the Osteoarthritis & RA Cream?",
      "How should the OA/RA Cream be applied?",
      "Who should not use the OA/RA Cream?",
      "What outcomes are expected with the OA/RA Cream?",
      "What is the Nerve Target Roll-On Pain Relief?",
      "How should the Roll-On Pain Relief be applied?",
      "Who should not use the Roll-On Pain Relief?",
      "What outcomes are expected with the Roll-On Pain Relief?",
      "What outcomes are expected from the Hand & Foot Neuropathy System?",
      "What ingredients are in the Nerve & Neuropathy Cream?",
      "How does the Nerve & Neuropathy Cream provide relief?",
      "What ingredients are in the Osteoarthritis & RA Cream?",
      "How does the Osteoarthritis & RA Cream provide relief?",
      "What if the Hand & Foot Neuropathy System does not power on?",
      "What is the Osteoarthritis & Rheumatoid Arthritis (OA/RA) Cream?",
      "How should the OA/RA Cream be used?",
      "Can NerveSpa be used if I have open wounds or skin conditions?",
      "What warranty and return policy does NerveSpa offer?",
      "Are topicals covered by warranty or return policies?",
      "What warranty does NerveSpa offer?",
      "How does NerveSpa ensure safety?",
      "How do I clean and maintain QuakePlate?",
      "How do I register my NerveSpa product for warranty?",
      "What is included in the warranty?",
      "How do I clean and maintain the NerveSpa Footbath?",
      "How do I clean and maintain the conductive garments?",
      "How do I clean and store Knee Pro?",
      "How do I clean and store the Shoulder Pro?",
      "How do I clean and maintain the conductive garments?"
];

// Helper function to normalize text (same logic as before)
// 1. Lowercase
// 2. Remove '?'
// 3. Fix spaces
function normalize(text) {
    if (!text) return "";
    return text.toLowerCase().replace(/\?/g, "").replace(/\s+/g, " ").trim();
}

// Normalize the incoming input
const cleanIncoming = normalize(incomingQuestion);

// Check if the incoming question matches any predefined question
// We use .some() instead of .includes() so we can clean the list items on the fly
let outputValue;
const isMatch = predefinedQuestions.some(q => normalize(q) === cleanIncoming);

if (isMatch) {
    outputValue = '0';
} else {
    outputValue = '1';
}

// Return the output in n8n format
return [{
    json: {
        result: outputValue
    }
}];